language: go

go:
  - 1.9

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_install:
  - go get github.com/gorilla/mux
  - go get github.com/antchfx/xquery/html
  - go get github.com/stretchr/testify

script:
  - go test -v
